# Generated by Django 4.2.4 on 2023-12-19 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_useraddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='user',
        ),
    ]
